name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro site
        run: |
          cd apps/astro-site
          pnpm build

      - name: Build Slidev projects
        run: |          
          # Slidevプロジェクトをビルド
          for dir in apps/*/; do
            if [ -f "$dir/slides.md" ] && [[ ! "$dir" == _* ]]; then
              echo "Building $dir"
              cd "$dir"
              pnpm install
              pnpm exec slidev build
              pnpm exec slidev export --output slides.pdf
              
              echo "Build completed for $dir"
              echo "Contents of dist:"
              ls -la dist
              
              # 直接Astroのdistディレクトリにコピー
              dirname=$(basename "$dir")
              mkdir -p "apps/astro-site/dist/slides/$dirname"
              cp -rv dist/* "apps/astro-site/dist/slides/$dirname/"
              cp -v slides.pdf "apps/astro-site/dist/slides/$dirname/"
              
              cd "$GITHUB_WORKSPACE"
            fi
          done

      - name: Check File Tree
        run: |
          echo -e "\n=== File Tree ==="
          find apps/astro-site/dist -type f
          
          echo -e "\n=== Directory Structure with Sizes ==="
          du -ah apps/astro-site/dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/astro-site/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
