name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: Create slides directory structure
        run: mkdir -p apps/astro-site/public/slides

      - name: Build Slidev projects
        run: |          
          # まず各Slidevプロジェクトをビルド
          for dir in apps/*/; do
            if [ -f "$dir/slides.md" ] && [[ ! "$dir" == "_"* ]] && [[ ! "$dir" == "apps/astro-site/"* ]]; then
              echo "Building $dir"
              cd "$dir"
              pnpm install
              pnpm exec slidev build
              pnpm exec slidev export --output slides.pdf
              
              echo "Build completed for $dir"
              
              # Astroのpublicディレクトリにコピー（静的ファイルとして扱われる）
              dirname=$(basename "$dir")
              mkdir -p "../astro-site/public/slides/$dirname"
              cp -rv dist/* "../astro-site/public/slides/$dirname/"
              cp -v slides.pdf "../astro-site/public/slides/$dirname/"
              
              cd "$GITHUB_WORKSPACE"
            fi
          done

      - name: Build Astro site
        run: |
          cd apps/astro-site
          pnpm build
          
          # 確認のためディレクトリの内容を表示
          echo "Contents of dist/slides:"
          ls -la dist/slides || echo "dist/slides does not exist"
          echo "Contents of public/slides:"
          ls -la public/slides || echo "public/slides does not exist"

      - name: Check File Tree
        run: |
          echo -e "\n=== File Tree ==="
          find apps/astro-site/dist -type f | sort
          
          echo -e "\n=== Directory Structure with Sizes ==="
          du -ah apps/astro-site/dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/astro-site/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
